(() => {
  "use strict";
  const CENTER=[46.2563,-72.9417], ADDRESS_FILE="louiseville_adresses.json", HYDRANT_FILE="firemap-2026-07-30 2.geojson";
  const $=id=>document.getElementById(id), state={addresses:[],hydrants:[],markers:new Map(),selected:null,user:null,lastMapClick:null,cloudReady:false,cloudHasData:false,deferredInstall:null,nearest:[],history:[]};
  const map=L.map("map",{zoomControl:true}).setView(CENTER,14);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"&copy; OpenStreetMap"}).addTo(map);
  const hydrantLayer=L.layerGroup().addTo(map), interventionLayer=L.layerGroup().addTo(map), resourceLayer=L.layerGroup().addTo(map), userLayer=L.layerGroup().addTo(map);
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const norm=s=>String(s??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
  const toast=m=>{const t=$("toast");t.textContent=m;t.classList.remove("hidden");clearTimeout(toast.x);toast.x=setTimeout(()=>t.classList.add("hidden"),2600)};
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2);
  const statusLabel=s=>s==="maintenance"?"Entretien":s==="inactive"?"Hors service":"Active";
  function canonical(p){return {id:String(p.id||uid()),name:String(p.name||p.numero||"Sans numéro"),address:String(p.address||p.adresse||""),lat:Number(p.lat),lng:Number(p.lng),status:p.status||"active",hydrantColor:p.hydrantColor||p.color||"blue",outletType:p.outletType||"",flowRate:p.flowRate||"",inspection:p.inspection||"",notes:p.notes||"",type:"station"}}
  async function loadBase(){
    try{const [a,g]=await Promise.all([fetch(ADDRESS_FILE,{cache:"no-cache"}).then(r=>r.json()),fetch(HYDRANT_FILE,{cache:"no-cache"}).then(r=>r.json())]);state.addresses=a;updateAddressCounts();const base=(g.features||[]).map(f=>canonical({...f.properties,lat:f.geometry.coordinates[1],lng:f.geometry.coordinates[0]})).filter(p=>isFinite(p.lat)&&isFinite(p.lng));setHydrants(base,"local");}catch(e){console.error(e);toast("Erreur de chargement des données.")}
  }
  function setHydrants(items,source){state.hydrants=items.map(canonical);renderMarkers();renderHydrantList();renderInspections();$("hydrantCount").textContent=`${state.hydrants.length} bornes affichées`;if(state.selected)renderNearest();if(source==="cloud")state.cloudHasData=true}
  function iconFor(p){return L.divIcon({className:"custom-hydrant",html:`<div class="hydrant-icon ${esc(p.hydrantColor)}">H</div>`,iconSize:[30,30],iconAnchor:[15,15],popupAnchor:[0,-13]})}
  function renderMarkers(){hydrantLayer.clearLayers();state.markers.clear();state.hydrants.forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:iconFor(p)}).bindPopup(`<strong>Borne ${esc(p.name)}</strong><br>${esc(p.address)}<br><span class="status ${esc(p.status)}">${statusLabel(p.status)}</span><br><button onclick="window.editFireHydrant('${esc(p.id)}')">Modifier</button>`).addTo(hydrantLayer);state.markers.set(p.id,m)})}
  function renderHydrantList(){const q=norm($("hydrantSearch").value),sf=$("statusFilter").value;const items=state.hydrants.filter(p=>(!sf||p.status===sf)&&(!q||norm([p.name,p.address,p.status,p.notes].join(" ")).includes(q))).sort((a,b)=>a.name.localeCompare(b.name,"fr",{numeric:true}));$("hydrantList").innerHTML=items.map(p=>`<article class="card-item"><div class="hydrant-badge ${esc(p.hydrantColor)}">H</div><div class="card-content"><h3>Borne ${esc(p.name)}</h3><span class="status ${esc(p.status)}">${statusLabel(p.status)}</span><p>${esc(p.address)||"Adresse non inscrite"}</p><p>${p.inspection?"Inspection : "+esc(p.inspection):"Inspection non inscrite"}${p.flowRate?" · "+esc(p.flowRate)+" L/min":""}</p><div class="card-actions"><button class="secondary" data-show="${esc(p.id)}">Voir</button><button class="secondary" data-edit="${esc(p.id)}">Modifier</button><button class="primary" data-nav="${esc(p.id)}">GPS</button></div></div></article>`).join("")||`<div class="card-item">Aucune borne trouvée.</div>`}
  function renderInspections(){const now=new Date(),old=new Date();old.setFullYear(old.getFullYear()-1);let current=0,due=0,missing=0;const sorted=[...state.hydrants].sort((a,b)=>(a.inspection||"").localeCompare(b.inspection||""));sorted.forEach(p=>{if(!p.inspection)missing++;else if(new Date(p.inspection)<old)due++;else current++});$("inspectionStats").innerHTML=`<div><strong>${current}</strong><span>À jour</span></div><div><strong>${due}</strong><span>À inspecter</span></div><div><strong>${missing}</strong><span>Sans date</span></div>`;$("inspectionList").innerHTML=sorted.map(p=>`<article class="card-item"><div class="hydrant-badge ${esc(p.hydrantColor)}">H</div><div class="card-content"><h3>Borne ${esc(p.name)}</h3><p>${esc(p.address)}</p><p>${p.inspection?`Dernière inspection : ${esc(p.inspection)}`:"Aucune inspection inscrite"}</p><div class="card-actions"><button class="secondary" data-edit="${esc(p.id)}">Mettre à jour</button></div></div></article>`).join("")}
  function search(query){const terms=norm(query).split(" ").filter(Boolean);if(!terms.length)return[];return state.addresses.filter(a=>terms.every(t=>a.recherche.includes(t))).sort((a,b)=>a.adresse.localeCompare(b.adresse,"fr",{numeric:true})).slice(0,35)}
  function updateAddressCounts(){const n=state.addresses.length.toLocaleString("fr-CA");$("searchStatus").textContent=`${n} adresses chargées`;$("searchStatusFull").textContent=`${n} adresses chargées`}
  function renderResults(inputId,boxId,statusId){const input=$(inputId),items=search(input.value),box=$(boxId);box.innerHTML="";if(!input.value.trim()){updateAddressCounts();return}$(statusId).textContent=items.length?`${items.length} résultat(s) affiché(s)`:"Aucune adresse trouvée";box.innerHTML=items.map((a,i)=>`<button class="result-item" data-address-index="${state.addresses.indexOf(a)}"><span class="pin">📍</span><span><strong>${esc(a.adresse)}</strong><small>${a.lat.toFixed(6)}, ${a.lng.toFixed(6)}</small></span></button>`).join("")}
  function interventionIcon(){return L.divIcon({className:"custom-hydrant",html:`<div class="intervention-pin pulse-ring"><span>🔥</span></div>`,iconSize:[38,38],iconAnchor:[8,34],popupAnchor:[10,-31]})}
  function saveHistory(a){const item={adresse:a.adresse,lat:a.lat,lng:a.lng,at:new Date().toISOString()};state.history=[item,...state.history.filter(x=>x.adresse!==item.adresse)].slice(0,8);localStorage.setItem("firemap-interventions",JSON.stringify(state.history));renderHistory()}
  function loadHistory(){try{state.history=JSON.parse(localStorage.getItem("firemap-interventions")||"[]")}catch(_){state.history=[]}renderHistory()}
  function renderHistory(){const box=$("recentInterventions");if(!box)return;box.innerHTML=state.history.length?state.history.map((x,i)=>`<button class="recent-item" data-history="${i}"><strong>${esc(x.adresse)}</strong><span>${new Date(x.at).toLocaleString("fr-CA",{dateStyle:"short",timeStyle:"short"})}</span></button>`).join(""):`<span class="muted">Aucune intervention récente.</span>`}
  function computeNearest(){if(!state.selected){state.nearest=[];return[]}state.nearest=state.hydrants.filter(p=>p.status!=="inactive").map(p=>({...p,distance:distance(state.selected,p)})).sort((a,b)=>a.distance-b.distance).slice(0,3);return state.nearest}
  function renderNearest(){const items=computeNearest(),box=$("nearestList");resourceLayer.clearLayers();if(!items.length){box.innerHTML=`<span class="muted">Aucune borne active disponible.</span>`;$("nearestText").textContent="Aucune borne active";return}$("nearestText").textContent=`Borne ${items[0].name} à environ ${Math.round(items[0].distance)} m`;box.innerHTML=items.map((p,i)=>`<div class="nearest-item"><div class="nearest-rank">${i+1}</div><div class="nearest-info"><strong>Borne ${esc(p.name)} · ${Math.round(p.distance)} m</strong><span>${esc(p.address)||"Adresse non inscrite"}${p.flowRate?` · ${esc(p.flowRate)} L/min`:""}</span></div><div class="nearest-actions"><button class="mini-map" data-nearest-show="${esc(p.id)}">Carte</button><button class="mini-gps" data-nav="${esc(p.id)}">GPS</button></div></div>`).join("");items.forEach((p,i)=>L.polyline([[state.selected.lat,state.selected.lng],[p.lat,p.lng]],{color:i===0?"#dc2626":"#64748b",weight:i===0?4:2,opacity:.72,className:"leaflet-intervention-line"}).addTo(resourceLayer))}
  function selectAddress(a,remember=true){state.selected=a;$("addressSearch").value=a.adresse;$("addressSearchFull").value=a.adresse;$("results").innerHTML=$("resultsFull").innerHTML="";$("interventionCard").classList.remove("hidden");$("selectedAddress").textContent=a.adresse;interventionLayer.clearLayers();resourceLayer.clearLayers();L.marker([a.lat,a.lng],{icon:interventionIcon()}).bindPopup(`<strong>🔥 Intervention</strong><br>${esc(a.adresse)}`).addTo(interventionLayer).openPopup();renderNearest();if(remember)saveHistory(a);map.setView([a.lat,a.lng],17);showView("map")}
  function clearIntervention(){state.selected=null;state.nearest=[];interventionLayer.clearLayers();resourceLayer.clearLayers();$("interventionCard").classList.add("hidden");$("addressSearch").value=$("addressSearchFull").value="";updateAddressCounts();map.setView(CENTER,14)}
  const navUrl=(lat,lng)=>/iPhone|iPad|iPod/i.test(navigator.userAgent)?`https://maps.apple.com/?daddr=${lat},${lng}&dirflg=d`:`https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=driving`;
  function distance(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
  function nearest(){if(!state.selected)return toast("Choisissez d’abord une adresse.");const items=computeNearest();renderNearest();if(!items.length)return;map.fitBounds([[state.selected.lat,state.selected.lng],...items.map(p=>[p.lat,p.lng])],{padding:[45,45]});state.markers.get(items[0].id)?.openPopup()}
  function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));closeDrawer();if(name==="map")setTimeout(()=>map.invalidateSize(),100)}
  function openDrawer(){$("drawer").classList.add("open");$("backdrop").classList.remove("hidden")}
  function closeDrawer(){$("drawer").classList.remove("open");$("backdrop").classList.add("hidden")}
  function openForm(p=null){const d=$("hydrantDialog"),pos=state.lastMapClick||state.user||{lat:map.getCenter().lat,lng:map.getCenter().lng};$("modalTitle").textContent=p?`Modifier la borne ${p.name}`:"Ajouter une borne";$("hydrantId").value=p?.id||"";$("hydrantName").value=p?.name||"";$("hydrantStatus").value=p?.status||"active";$("hydrantAddress").value=p?.address||"";$("hydrantLat").value=p?.lat??pos.lat.toFixed(7);$("hydrantLng").value=p?.lng??pos.lng.toFixed(7);$("hydrantColor").value=p?.hydrantColor||"blue";$("outletType").value=p?.outletType||"";$("flowRate").value=p?.flowRate||"";$("inspectionDate").value=p?.inspection||"";$("hydrantNotes").value=p?.notes||"";$("deleteHydrant").classList.toggle("hidden",!p);d.showModal()}
  async function saveForm(){const p=canonical({id:$("hydrantId").value||uid(),name:$("hydrantName").value,address:$("hydrantAddress").value,lat:$("hydrantLat").value,lng:$("hydrantLng").value,status:$("hydrantStatus").value,hydrantColor:$("hydrantColor").value,outletType:$("outletType").value,flowRate:$("flowRate").value,inspection:$("inspectionDate").value,notes:$("hydrantNotes").value});if(!isFinite(p.lat)||!isFinite(p.lng))return toast("Coordonnées invalides.");const i=state.hydrants.findIndex(x=>x.id===p.id);if(i>=0)state.hydrants[i]=p;else state.hydrants.push(p);setHydrants(state.hydrants,"local");$("hydrantDialog").close();try{if(window.fireMapCloud?.configured)await window.fireMapCloud.savePoint(p);toast("Borne enregistrée et synchronisée.")}catch(e){console.error(e);toast("Borne enregistrée localement, erreur Firebase.")}}
  async function removeCurrent(){const id=$("hydrantId").value;if(!id||!confirm("Supprimer définitivement cette borne ?"))return;state.hydrants=state.hydrants.filter(p=>p.id!==id);setHydrants(state.hydrants,"local");$("hydrantDialog").close();try{if(window.fireMapCloud?.configured)await window.fireMapCloud.deletePoint(id);toast("Borne supprimée.")}catch(e){toast("Suppression locale seulement.")}}
  function locate(){if(!navigator.geolocation)return toast("GPS non disponible.");navigator.geolocation.getCurrentPosition(p=>{state.user={lat:p.coords.latitude,lng:p.coords.longitude};userLayer.clearLayers();L.circleMarker([state.user.lat,state.user.lng],{radius:9,color:"#fff",weight:3,fillColor:"#2563eb",fillOpacity:1}).bindPopup("Votre position").addTo(userLayer).openPopup();map.setView([state.user.lat,state.user.lng],16)},()=>toast("Autorisez la localisation dans Safari."),{enableHighAccuracy:true,timeout:12000,maximumAge:5000})}
  function connectCloud(){const start=()=>{const c=window.fireMapCloud;if(!c?.configured){$("syncTitle").textContent="Mode local";$("syncText").textContent="Firebase non connecté";return}$("syncTitle").textContent="Synchronisation active";$("syncText").textContent="Tous les appareils sont reliés";$("syncDot").classList.add("ok");c.subscribe(async data=>{if(data.length){setHydrants(data,"cloud")}else if(!state.cloudHasData&&state.hydrants.length){try{await c.saveMany(state.hydrants);toast("Bornes initiales envoyées dans Firebase.")}catch(e){console.error(e)}}},e=>{console.error(e);$("syncTitle").textContent="Erreur Firebase"})};if(window.fireMapCloud)start();else window.addEventListener("firemap-cloud-ready",start,{once:true})}
  document.addEventListener("click",e=>{const v=e.target.closest("[data-view]");if(v)showView(v.dataset.view);const ai=e.target.closest("[data-address-index]");if(ai)selectAddress(state.addresses[Number(ai.dataset.addressIndex)]);const edit=e.target.closest("[data-edit]");if(edit)openForm(state.hydrants.find(p=>p.id===edit.dataset.edit));const show=e.target.closest("[data-show]");if(show){const p=state.hydrants.find(x=>x.id===show.dataset.show);showView("map");map.setView([p.lat,p.lng],18);state.markers.get(p.id)?.openPopup()}const nav=e.target.closest("[data-nav]");if(nav){const p=state.hydrants.find(x=>x.id===nav.dataset.nav);if(p)location.href=navUrl(p.lat,p.lng)}const ns=e.target.closest("[data-nearest-show]");if(ns){const p=state.hydrants.find(x=>x.id===ns.dataset.nearestShow);if(p){map.setView([p.lat,p.lng],18);state.markers.get(p.id)?.openPopup()}}const hi=e.target.closest("[data-history]");if(hi){const x=state.history[Number(hi.dataset.history)];if(x)selectAddress(x,false)}});
  [["addressSearch","results","searchStatus"],["addressSearchFull","resultsFull","searchStatusFull"]].forEach(([i,b,s])=>$(i).addEventListener("input",()=>renderResults(i,b,s)));$("clearSearch").onclick=()=>{$("addressSearch").value="";$("results").innerHTML="";updateAddressCounts()};$("clearSearchFull").onclick=()=>{$("addressSearchFull").value="";$("resultsFull").innerHTML="";updateAddressCounts()};
  $("menuBtn").onclick=$("bottomMore").onclick=openDrawer;$("closeDrawer").onclick=$("backdrop").onclick=closeDrawer;$("clearIntervention").onclick=clearIntervention;$("clearHistory").onclick=()=>{state.history=[];localStorage.removeItem("firemap-interventions");renderHistory()};[$("drawerAdd"),$("mapAddBtn"),$("addHydrantTop"),$("bottomAdd")].forEach(b=>b.onclick=()=>openForm());$("locateBtn").onclick=locate;$("gpsBtn").onclick=()=>state.selected?location.href=navUrl(state.selected.lat,state.selected.lng):toast("Choisissez une adresse.");$("nearestBtn").onclick=nearest;$("hydrantToggle").onchange=e=>e.target.checked?hydrantLayer.addTo(map):map.removeLayer(hydrantLayer);$("hydrantSearch").oninput=renderHydrantList;$("statusFilter").onchange=renderHydrantList;$("closeModal").onclick=$("cancelModal").onclick=()=>$("hydrantDialog").close();$("hydrantForm").onsubmit=e=>{e.preventDefault();saveForm()};$("deleteHydrant").onclick=removeCurrent;map.on("click",e=>state.lastMapClick={lat:e.latlng.lat,lng:e.latlng.lng});window.editFireHydrant=id=>openForm(state.hydrants.find(p=>p.id===id));
  window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredInstall=e;$("installBtn").classList.remove("hidden")});$("installBtn").onclick=async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null}};
  if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));loadHistory();loadBase().then(connectCloud);
})();
